import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Copy, Share2, Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';
import {
  type WorkMode, type TerrazzoStyle, type PatternType,
  WORK_MODES, formatCurrency,
} from '@/lib/pricingConfig';
import { loadAdminConfig, calculateRateFromConfig, calculateTotalFromConfig } from '@/lib/usePricingConfig';

interface ClientData {
  name: string;
  phone: string;
  location: string;
}

interface LiveSummaryProps {
  client: ClientData;
  area: number;
  workMode: WorkMode;
  style: TerrazzoStyle;
  pattern: PatternType;
}

export const LiveSummary = ({ client, area, workMode, style, pattern }: LiveSummaryProps) => {
  const { toast } = useToast();
  const adminConfig = loadAdminConfig();
  const rate = calculateRateFromConfig(adminConfig, style, workMode, pattern);
  const total = calculateTotalFromConfig(adminConfig, area, style, workMode, pattern);
  const modeName = WORK_MODES.find(m => m.id === workMode)!.name;
  const styleName = adminConfig.styles.find(s => s.id === style)!.name;
  const patternName = adminConfig.patterns.find(p => p.id === pattern)!.name;
  const patternMultiplier = adminConfig.patterns.find(p => p.id === pattern)!.multiplier;
  const styleConfig = adminConfig.styles.find(s => s.id === style)!;
  const date = new Date().toLocaleDateString('en-UG', { year: 'numeric', month: 'long', day: 'numeric' });

  const getBaseRate = () => {
    if (workMode === 'materials') return styleConfig.materialsRate;
    if (workMode === 'labour') return styleConfig.labourRate;
    return styleConfig.materialsRate + styleConfig.labourRate;
  };

  const getQuoteText = () => `
TERRAZZO QUOTATION PRO
========================
Date: ${date}

CLIENT: ${client.name}
Phone: ${client.phone}
Location: ${client.location}

PROJECT:
Area: ${area.toFixed(2)} m²
Work Mode: ${modeName}
Style: ${styleName}
Pattern: ${patternName}

Rate: ${formatCurrency(rate)}/m²
GRAND TOTAL: ${formatCurrency(total)}

Quotation valid for 14 days.
Generated by Terrazzo Quotation Pro
`.trim();

  const handleCopy = async () => {
    await navigator.clipboard.writeText(getQuoteText());
    toast({ title: 'Copied', description: 'Quotation copied to clipboard' });
  };

  const handleWhatsApp = () => {
    window.open(`https://wa.me/?text=${encodeURIComponent(getQuoteText())}`, '_blank');
  };

  const handlePDF = () => {
    const doc = new jsPDF();
    const pw = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(22);
    doc.setFont(undefined, 'bold');
    doc.text('TERRAZZO QUOTATION PRO', pw / 2, 22, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Date: ${date}`, pw / 2, 30, { align: 'center' });

    // Divider
    doc.setDrawColor(52, 120, 198);
    doc.setLineWidth(0.8);
    doc.line(20, 35, pw - 20, 35);

    // Client details
    let y = 45;
    doc.setFontSize(13);
    doc.setFont(undefined, 'bold');
    doc.text('CLIENT DETAILS', 20, y); y += 10;
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.text(`Name: ${client.name}`, 20, y); y += 7;
    doc.text(`Phone: ${client.phone}`, 20, y); y += 7;
    doc.text(`Location: ${client.location}`, 20, y); y += 14;

    // Project details
    doc.setFontSize(13);
    doc.setFont(undefined, 'bold');
    doc.text('PROJECT DETAILS', 20, y); y += 10;
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.text(`Area: ${area.toFixed(2)} m²`, 20, y); y += 7;
    doc.text(`Work Mode: ${modeName}`, 20, y); y += 7;
    doc.text(`Terrazzo Style: ${styleName}`, 20, y); y += 7;
    doc.text(`Pattern: ${patternName}`, 20, y); y += 14;

    // Cost breakdown table
    doc.setFontSize(13);
    doc.setFont(undefined, 'bold');
    doc.text('COST BREAKDOWN', 20, y); y += 10;

    // Table header
    doc.setFillColor(52, 120, 198);
    doc.rect(20, y - 5, pw - 40, 8, 'F');
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.setFont(undefined, 'bold');
    doc.text('Description', 25, y);
    doc.text('Amount', pw - 25, y, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    y += 10;

    // Table rows
    doc.setFont(undefined, 'normal');
    const rows = [
      [`Base rate (${styleName})`, `${formatCurrency(getBaseRate())}/m²`],
      [`Pattern adjustment (${patternName})`, `×${patternMultiplier.toFixed(2)}`],
      [`Adjusted rate per m²`, `${formatCurrency(rate)}/m²`],
      [`Project area`, `${area.toFixed(2)} m²`],
    ];

    rows.forEach(([desc, val], i) => {
      if (i % 2 === 0) {
        doc.setFillColor(245, 247, 250);
        doc.rect(20, y - 5, pw - 40, 8, 'F');
      }
      doc.text(desc, 25, y);
      doc.text(val, pw - 25, y, { align: 'right' });
      y += 8;
    });

    // Grand total
    y += 4;
    doc.setFillColor(52, 120, 198);
    doc.rect(20, y - 6, pw - 40, 12, 'F');
    doc.setFontSize(13);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('GRAND TOTAL', 25, y + 1);
    doc.text(formatCurrency(total), pw - 25, y + 1, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    y += 20;

    // Notes
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('NOTES', 20, y); y += 8;
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    const notes = [
      '• Prices based on stated area and standard site conditions.',
      '• Subfloor assumed level and structurally sound.',
      '• Quotation valid for 14 days from the date above.',
      '• Generated by Terrazzo Quotation Pro.',
    ];
    notes.forEach(n => { doc.text(n, 25, y); y += 6; });

    // Footer
    doc.setFontSize(8);
    doc.setFont(undefined, 'italic');
    doc.text('Terrazzo Quotation Pro', pw / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

    doc.save(`Terrazzo_Quote_${client.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
    toast({ title: 'PDF Downloaded', description: 'Professional quotation saved' });
  };

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-semibold">Quotation Summary</h2>

      <Card className="p-6">
        <div className="text-center mb-6">
          <h1 className="text-2xl font-bold text-primary">Terrazzo Quotation Pro</h1>
          <p className="text-sm text-muted-foreground">{date}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div>
            <h3 className="font-semibold text-lg mb-3 text-primary">Client</h3>
            <div className="space-y-1 text-sm">
              <div><span className="font-medium">Name:</span> {client.name}</div>
              <div><span className="font-medium">Phone:</span> {client.phone}</div>
              <div><span className="font-medium">Location:</span> {client.location}</div>
            </div>
          </div>
          <div>
            <h3 className="font-semibold text-lg mb-3 text-primary">Project</h3>
            <div className="space-y-1 text-sm">
              <div><span className="font-medium">Area:</span> {area.toFixed(2)} m²</div>
              <div className="flex items-center gap-2 flex-wrap mt-2">
                <Badge variant="secondary">{modeName}</Badge>
                <Badge variant="secondary">{styleName}</Badge>
                <Badge variant="secondary">{patternName}</Badge>
              </div>
            </div>
          </div>
        </div>

        {/* Cost breakdown */}
        <div className="border rounded-lg overflow-hidden mb-6">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-primary text-primary-foreground">
                <th className="text-left p-3 font-semibold">Description</th>
                <th className="text-right p-3 font-semibold">Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b bg-muted/30">
                <td className="p-3">Base rate ({styleName})</td>
                <td className="p-3 text-right">{formatCurrency(getBaseRate())}/m²</td>
              </tr>
              <tr className="border-b">
                <td className="p-3">Pattern adjustment ({patternName})</td>
                <td className="p-3 text-right">×{patternMultiplier.toFixed(2)}</td>
              </tr>
              <tr className="border-b bg-muted/30">
                <td className="p-3 font-medium">Adjusted rate per m²</td>
                <td className="p-3 text-right font-medium">{formatCurrency(rate)}/m²</td>
              </tr>
              <tr className="border-b">
                <td className="p-3">Project area</td>
                <td className="p-3 text-right">{area.toFixed(2)} m²</td>
              </tr>
            </tbody>
            <tfoot>
              <tr className="bg-primary text-primary-foreground">
                <td className="p-3 font-bold text-lg">GRAND TOTAL</td>
                <td className="p-3 text-right font-bold text-lg">{formatCurrency(total)}</td>
              </tr>
            </tfoot>
          </table>
        </div>

        {/* Notes */}
        <div className="text-xs text-muted-foreground space-y-1 mb-6">
          <p>• Prices based on stated area and standard site conditions.</p>
          <p>• Subfloor assumed level and structurally sound.</p>
          <p>• Quotation valid for 14 days.</p>
        </div>
      </Card>

      {/* Action buttons */}
      <Card className="p-6">
        <div className="flex flex-col sm:flex-row gap-3">
          <Button onClick={handleCopy} variant="outline" className="flex-1">
            <Copy className="h-4 w-4 mr-2" />
            Copy to Clipboard
          </Button>
          <Button onClick={handleWhatsApp} className="flex-1 bg-success hover:bg-success/90">
            <Share2 className="h-4 w-4 mr-2" />
            Share on WhatsApp
          </Button>
          <Button onClick={handlePDF} variant="outline" className="flex-1">
            <Download className="h-4 w-4 mr-2" />
            Download PDF
          </Button>
        </div>
      </Card>
    </div>
  );
};
