import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Copy, Share2, Download, Eye, EyeOff } from 'lucide-react';
import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';

interface ClientData {
  name: string;
  phone: string;
  location: string;
  date: string;
}

interface ProjectData {
  area: number;
  unit: 'sqm' | 'sqft';
  phases: ('casting' | 'grinding')[];
}

interface QuotationDisplayProps {
  clientData: ClientData;
  projectData: ProjectData;
  total: number;
  formatCurrency: (amount: number) => string;
  onBack: () => void;
}

const MATERIAL_BREAKDOWN = {
  casting: [
    { item: 'Stones floor white', quantity: '60 bags', price: 15000 },
    { item: 'Stones floor black', quantity: '14 bags', price: 13000 },
    { item: 'Stones floor red', quantity: '10 bags', price: 13000 },
    { item: 'Stones skirting white', quantity: '9 bags', price: 15000 },
    { item: 'Stones skirting black', quantity: '11 bags', price: 13000 },
    { item: 'Stones skirting red', quantity: '4 bags', price: 13000 },
    { item: 'Stips', quantity: '3 bundles', price: 60000 },
    { item: 'Soft brush', quantity: '5', price: 12000 },
    { item: 'Black oxide', quantity: '20 kg', price: 8000 },
    { item: 'Concrete nails', quantity: '3 boxes', price: 5000 },
    { item: 'Wooden stips', quantity: '30', price: 1000 },
    { item: 'Ordinary cement', quantity: '52 bags', price: 33000 },
    { item: 'White cement', quantity: '10 bags', price: 65000 }
  ],
  grinding: [
    { item: 'Big machine Diamond', quantity: '2 sets', price: 150000 },
    { item: 'Grinder Diamond', quantity: '2 pcs', price: 60000 },
    { item: 'Pads 50(2*)', quantity: '3', price: 20000 },
    { item: 'Pads 100(2*)', quantity: '2', price: 20000 },
    { item: 'Pads 200(2*)', quantity: '2', price: 20000 },
    { item: 'Pads 300(2*)', quantity: '2', price: 20000 },
    { item: 'Pads 400(2*)', quantity: '2', price: 20000 },
    { item: 'Pads 500(2*)', quantity: '1', price: 20000 },
    { item: 'Grinder Pad holder', quantity: '4', price: 15000 },
    { item: 'Machine Pad holder', quantity: '4', price: 15000 },
    { item: 'Squeezer', quantity: '3', price: 10000 },
    { item: 'Polish', quantity: '20 L', price: 20000 },
    { item: 'Maintainer', quantity: '40 L', price: 10000 }
  ]
};

export const QuotationDisplay = ({ 
  clientData, 
  projectData, 
  total, 
  formatCurrency, 
  onBack 
}: QuotationDisplayProps) => {
  const [showMaterials, setShowMaterials] = useState(false);
  const { toast } = useToast();

  const getAreaInSqm = () => {
    return projectData.unit === 'sqft' ? projectData.area * 0.0929 : projectData.area;
  };

  const getQuoteText = () => {
    const area = getAreaInSqm();
    const phases = projectData.phases.join(' + ');
    
    return `
TERRAZZO QUOTATION PRO
========================

CLIENT DETAILS:
Name: ${clientData.name}
Phone: ${clientData.phone}
Location: ${clientData.location}
Date: ${clientData.date}

PROJECT DETAILS:
Area: ${area.toFixed(2)} m²
Phases: ${phases}
Total: ${formatCurrency(total)}

Generated by Terrazzo Quotation Pro
    `.trim();
  };

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(getQuoteText());
      toast({
        title: "Copied to Clipboard",
        description: "Quotation text copied successfully",
      });
    } catch (error) {
      toast({
        title: "Copy Failed",
        description: "Unable to copy to clipboard",
        variant: "destructive"
      });
    }
  };

  const handleShare = async () => {
    const text = getQuoteText();
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const area = getAreaInSqm();
    
    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('TERRAZZO QUOTATION PRO', 105, 20, { align: 'center' });
    
    // Client Details
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('CLIENT DETAILS:', 20, 40);
    
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Name: ${clientData.name}`, 20, 50);
    doc.text(`Phone: ${clientData.phone}`, 20, 60);
    doc.text(`Location: ${clientData.location}`, 20, 70);
    doc.text(`Date: ${clientData.date}`, 20, 80);
    
    // Project Details
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('PROJECT DETAILS:', 20, 100);
    
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Area: ${area.toFixed(2)} m²`, 20, 110);
    doc.text(`Phases: ${projectData.phases.join(' + ')}`, 20, 120);
    
    // Total
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('GRAND TOTAL:', 20, 140);
    doc.text(formatCurrency(total), 20, 155);
    
    // Material Breakdown if shown
    if (showMaterials) {
      let yPos = 175;
      
      projectData.phases.forEach(phase => {
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text(`${phase.charAt(0).toUpperCase() + phase.slice(1)} Phase Materials:`, 20, yPos);
        yPos += 15;
        
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        
        MATERIAL_BREAKDOWN[phase].forEach(material => {
          if (yPos > 270) {
            doc.addPage();
            yPos = 20;
          }
          doc.text(`${material.item} - ${material.quantity} - ${formatCurrency(material.price)}`, 20, yPos);
          yPos += 8;
        });
        
        yPos += 10;
      });
    }
    
    // Footer
    doc.setFontSize(8);
    doc.setFont(undefined, 'italic');
    doc.text('Generated by Terrazzo Quotation Pro', 105, doc.internal.pageSize.height - 10, { align: 'center' });
    
    // Save the PDF
    doc.save(`Terrazzo_Quote_${clientData.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
    
    toast({
      title: "PDF Downloaded",
      description: "Professional quotation PDF saved successfully",
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="outline" onClick={onBack}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Form
        </Button>
        <h2 className="text-2xl font-bold">Professional Quotation</h2>
      </div>

      {/* Quotation Card */}
      <Card className="p-8 shadow-elevated">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-primary mb-2">
            TERRAZZO QUOTATION PRO
          </h1>
          <div className="w-24 h-1 bg-gradient-primary mx-auto rounded"></div>
        </div>

        {/* Client Info */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          <div>
            <h3 className="font-semibold text-lg mb-4 text-primary">Client Details</h3>
            <div className="space-y-2">
              <div><span className="font-medium">Name:</span> {clientData.name}</div>
              <div><span className="font-medium">Phone:</span> {clientData.phone}</div>
              <div><span className="font-medium">Location:</span> {clientData.location}</div>
              <div><span className="font-medium">Date:</span> {clientData.date}</div>
            </div>
          </div>
          
          <div>
            <h3 className="font-semibold text-lg mb-4 text-primary">Project Details</h3>
            <div className="space-y-2">
              <div><span className="font-medium">Area:</span> {getAreaInSqm().toFixed(2)} m²</div>
              <div><span className="font-medium">Phases:</span> {projectData.phases.join(' + ')}</div>
              <div className="flex gap-2 mt-2">
                {projectData.phases.map(phase => (
                  <Badge key={phase} variant="secondary">
                    {phase.charAt(0).toUpperCase() + phase.slice(1)}
                  </Badge>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Total */}
        <div className="bg-gradient-primary/10 p-6 rounded-lg mb-6">
          <div className="text-center">
            <h3 className="text-2xl font-bold text-primary mb-2">
              GRAND TOTAL
            </h3>
            <div className="text-4xl font-bold text-primary">
              {formatCurrency(total)}
            </div>
            <p className="text-muted-foreground mt-2">
              All inclusive professional terrazzo work
            </p>
          </div>
        </div>

        {/* Material Breakdown Toggle */}
        <div className="mb-6">
          <Button 
            variant="outline" 
            onClick={() => setShowMaterials(!showMaterials)}
            className="w-full"
          >
            {showMaterials ? <EyeOff className="h-4 w-4 mr-2" /> : <Eye className="h-4 w-4 mr-2" />}
            {showMaterials ? 'Hide' : 'Show'} Material Breakdown
          </Button>
        </div>

        {/* Material Breakdown */}
        {showMaterials && (
          <div className="space-y-6 mb-8">
            {projectData.phases.map(phase => (
              <div key={phase}>
                <h4 className="font-semibold text-lg mb-3 text-primary capitalize">
                  {phase} Phase Materials
                </h4>
                <div className="border rounded-lg overflow-hidden">
                  <table className="w-full">
                    <thead className="bg-muted">
                      <tr>
                        <th className="text-left p-3">Item</th>
                        <th className="text-left p-3">Quantity</th>
                        <th className="text-right p-3">Price (UGX)</th>
                      </tr>
                    </thead>
                    <tbody>
                      {MATERIAL_BREAKDOWN[phase].map((material, index) => (
                        <tr key={index} className="border-t">
                          <td className="p-3">{material.item}</td>
                          <td className="p-3">{material.quantity}</td>
                          <td className="p-3 text-right">{formatCurrency(material.price)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-3">
          <Button onClick={handleCopyToClipboard} variant="outline" className="flex-1">
            <Copy className="h-4 w-4 mr-2" />
            Copy to Clipboard
          </Button>
          
          <Button onClick={handleShare} className="flex-1 bg-success hover:bg-success/90">
            <Share2 className="h-4 w-4 mr-2" />
            Share on WhatsApp
          </Button>
          
          <Button variant="outline" className="flex-1" onClick={handleDownloadPDF}>
            <Download className="h-4 w-4 mr-2" />
            Download PDF
          </Button>
        </div>
      </Card>
    </div>
  );
};