import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Copy, Share2, Download } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';
import { EditableTable } from './EditableTable';
import { MaterialItem, calculateCastingMaterials, calculateGrindingMaterials } from '@/lib/materialCalculations';

interface ClientData {
  name: string;
  phone: string;
  location: string;
  date: string;
}

interface ProjectData {
  area: number;
  unit: 'sqm' | 'sqft';
  phases: ('casting' | 'grinding')[];
}

interface QuotationDisplayProps {
  clientData: ClientData;
  projectData: ProjectData;
  total: number;
  formatCurrency: (amount: number) => string;
  onBack: () => void;
}

export const QuotationDisplay = ({ 
  clientData, 
  projectData, 
  total, 
  formatCurrency, 
  onBack 
}: QuotationDisplayProps) => {
  const [castingMaterials, setCastingMaterials] = useState<MaterialItem[]>([]);
  const [grindingMaterials, setGrindingMaterials] = useState<MaterialItem[]>([]);
  const { toast } = useToast();

  const getAreaInSqm = () => {
    return projectData.unit === 'sqft' ? projectData.area * 0.0929 : projectData.area;
  };

  // Initialize materials on mount
  useEffect(() => {
    const area = getAreaInSqm();
    if (projectData.phases.includes('casting')) {
      setCastingMaterials(calculateCastingMaterials(area));
    }
    if (projectData.phases.includes('grinding')) {
      setGrindingMaterials(calculateGrindingMaterials(area));
    }
  }, [projectData.phases, projectData.area, projectData.unit]);

  const handleCastingMaterialsChange = (newMaterials: MaterialItem[]) => {
    setCastingMaterials(newMaterials);
  };

  const handleGrindingMaterialsChange = (newMaterials: MaterialItem[]) => {
    setGrindingMaterials(newMaterials);
  };

  const getUpdatedTotal = () => {
    const castingTotal = castingMaterials.reduce((sum, item) => sum + item.total, 0);
    const grindingTotal = grindingMaterials.reduce((sum, item) => sum + item.total, 0);
    return castingTotal + grindingTotal;
  };

  const getQuoteText = () => {
    const area = getAreaInSqm();
    const phases = projectData.phases.join(' + ');
    const updatedTotal = getUpdatedTotal();
    
    return `
TERRAZZO QUOTATION PRO
========================

CLIENT DETAILS:
Name: ${clientData.name}
Phone: ${clientData.phone}
Location: ${clientData.location}
Date: ${clientData.date}

PROJECT DETAILS:
Area: ${area.toFixed(2)} m²
Phases: ${phases}
Total: ${formatCurrency(updatedTotal)}

Generated by Terrazzo Quotation Pro
    `.trim();
  };

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(getQuoteText());
      toast({
        title: "Copied to Clipboard",
        description: "Quotation text copied successfully",
      });
    } catch (error) {
      toast({
        title: "Copy Failed",
        description: "Unable to copy to clipboard",
        variant: "destructive"
      });
    }
  };

  const handleShare = async () => {
    const text = getQuoteText();
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const area = getAreaInSqm();
    const updatedTotal = getUpdatedTotal();
    
    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text('TERRAZZO QUOTATION PRO', 105, 20, { align: 'center' });
    
    // Client Details
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('CLIENT DETAILS:', 20, 40);
    
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Name: ${clientData.name}`, 20, 50);
    doc.text(`Phone: ${clientData.phone}`, 20, 60);
    doc.text(`Location: ${clientData.location}`, 20, 70);
    doc.text(`Date: ${clientData.date}`, 20, 80);
    
    // Project Details
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('PROJECT DETAILS:', 20, 100);
    
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Area: ${area.toFixed(2)} m²`, 20, 110);
    doc.text(`Phases: ${projectData.phases.join(' + ')}`, 20, 120);
    
    // Total
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('GRAND TOTAL:', 20, 140);
    doc.text(formatCurrency(updatedTotal), 20, 155);
    
    // Material Breakdown
    let yPos = 175;
    
    if (projectData.phases.includes('casting') && castingMaterials.length > 0) {
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text('CASTING PHASE MATERIALS:', 20, yPos);
      yPos += 15;
      
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      
      castingMaterials.forEach(material => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(`${material.item} - ${material.quantity} - ${formatCurrency(material.total)}`, 20, yPos);
        yPos += 8;
      });
      
      yPos += 10;
    }

    if (projectData.phases.includes('grinding') && grindingMaterials.length > 0) {
      if (yPos > 220) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text('GRINDING PHASE MATERIALS:', 20, yPos);
      yPos += 15;
      
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      
      grindingMaterials.forEach(material => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(`${material.item} - ${material.quantity} - ${formatCurrency(material.total)}`, 20, yPos);
        yPos += 8;
      });
    }
    
    // Footer
    doc.setFontSize(8);
    doc.setFont(undefined, 'italic');
    doc.text('Generated by Terrazzo Quotation Pro', 105, doc.internal.pageSize.height - 10, { align: 'center' });
    
    // Save the PDF
    doc.save(`Terrazzo_Quote_${clientData.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
    
    toast({
      title: "PDF Downloaded",
      description: "Professional quotation PDF saved successfully",
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="outline" onClick={onBack}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Form
        </Button>
        <h2 className="text-2xl font-bold">Professional Quotation</h2>
      </div>

      {/* Client & Project Summary Card */}
      <Card className="p-6">
        <div className="text-center mb-6">
          <h1 className="text-2xl font-bold text-primary mb-2">
            Quotation
          </h1>
        </div>

        {/* Client Info */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div>
            <h3 className="font-semibold text-lg mb-3 text-primary">Client Details</h3>
            <div className="space-y-2 text-sm">
              <div><span className="font-medium">Name:</span> {clientData.name}</div>
              <div><span className="font-medium">Phone:</span> {clientData.phone}</div>
              <div><span className="font-medium">Location:</span> {clientData.location}</div>
              <div><span className="font-medium">Date:</span> {clientData.date}</div>
            </div>
          </div>
          
          <div>
            <h3 className="font-semibold text-lg mb-3 text-primary">Project Details</h3>
            <div className="space-y-2 text-sm">
              <div><span className="font-medium">Area:</span> {getAreaInSqm().toFixed(2)} m²</div>
              <div><span className="font-medium">Phases:</span> {projectData.phases.join(' + ')}</div>
              <div className="flex gap-2 mt-3">
                {projectData.phases.map(phase => (
                  <Badge key={phase} variant="secondary">
                    {phase.charAt(0).toUpperCase() + phase.slice(1)}
                  </Badge>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Updated Total */}
        <div className="bg-primary/5 p-4 rounded-lg text-center">
          <h3 className="text-xl font-bold text-primary mb-2">
            Total: {formatCurrency(getUpdatedTotal())} shs
          </h3>
        </div>
      </Card>

      {/* Material Tables */}
      <div className="space-y-6">
        {projectData.phases.includes('casting') && (
          <EditableTable
            title="Quotation"
            phase="casting"
            data={castingMaterials}
            formatCurrency={formatCurrency}
            onDataChange={handleCastingMaterialsChange}
          />
        )}

        {projectData.phases.includes('grinding') && (
          <EditableTable
            title="Quotation"
            phase="grinding"
            data={grindingMaterials}
            formatCurrency={formatCurrency}
            onDataChange={handleGrindingMaterialsChange}
          />
        )}
      </div>

      {/* Action Buttons */}
      <Card className="p-6">
        <div className="flex flex-col sm:flex-row gap-3">
          <Button onClick={handleCopyToClipboard} variant="outline" className="flex-1">
            <Copy className="h-4 w-4 mr-2" />
            Copy to Clipboard
          </Button>
          
          <Button onClick={handleShare} className="flex-1 bg-success hover:bg-success/90">
            <Share2 className="h-4 w-4 mr-2" />
            Share on WhatsApp
          </Button>
          
          <Button variant="outline" className="flex-1" onClick={handleDownloadPDF}>
            <Download className="h-4 w-4 mr-2" />
            Download PDF
          </Button>
        </div>
      </Card>
    </div>
  );
};