// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlzrmbedscmnmuzhfwkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsenJtYmVkc2Ntbm11emhmd2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NTIxMTUsImV4cCI6MjA1NzAyODExNX0.nNTBRQxW3gpWzeBcgnlETuHNG7MVwEX5TweaOPaz9Ss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});